In [120]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import (
    mean_squared_error,
    r2_score,
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [121]:
df = pd.read_csv('/content/heart_disease.csv')

In [122]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [123]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [125]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [126]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [127]:
df.duplicated().sum()

np.int64(1)

In [128]:
df.drop_duplicates(inplace=True)

In [129]:
# checking and removing the ouliers wiht the interquartile range
for col in df.select_dtypes(include=np.number).columns :
  Q1 = df[col].quantile(.25)
  Q3 = df[col].quantile(.75)
  IQR = Q3 - Q1
  lower = Q1 - 1.5 * IQR
  Upper = Q3 + 1.5 * IQR
  df[col] = df[col].clip(lower,Upper)

In [130]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,302.00000,302.000000,302.000000,302.000000,302.000000,302.0,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000
mean,54.42053,0.682119,0.963576,131.258278,245.377070,0.0,0.526490,149.612997,0.327815,1.027815,1.397351,0.665563,2.317881,0.543046
std,9.04797,0.466426,1.032044,16.605232,47.486683,0.0,0.526027,22.765983,0.470196,1.110395,0.616274,0.880241,0.601724,0.498970
min,29.00000,0.000000,0.000000,94.000000,126.000000,0.0,0.000000,84.125000,0.000000,0.000000,0.000000,0.000000,0.500000,0.000000
25%,48.00000,0.000000,0.000000,120.000000,211.000000,0.0,0.000000,133.250000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.50000,1.000000,1.000000,130.000000,240.500000,0.0,1.000000,152.500000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.00000,1.000000,2.000000,140.000000,274.750000,0.0,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.00000,1.000000,3.000000,170.000000,370.375000,0.0,2.000000,202.000000,1.000000,4.000000,2.000000,2.500000,3.000000,1.000000

In [131]:
X = df.drop("target", axis=1)
y = df["target"]

In [132]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=20)

In [133]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

model = RandomForestClassifier(
    n_estimators=200,
    random_state=20
)

model.fit(X_train, y_train)

y_test_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_test_pred))

Accuracy: 0.8852459016393442

Confusion Matrix:
[[22  1]
 [ 6 32]]

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.96      0.86        23
           1       0.97      0.84      0.90        38

    accuracy                           0.89        61
   macro avg       0.88      0.90      0.88        61
weighted avg       0.90      0.89      0.89        61

In [134]:
!pip install streamlit -q
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

(Reading database ... 118247 files and directories currently installed.)
Preparing to unpack cloudflared-linux-amd64.deb ...
Unpacking cloudflared (2026.6.1) over (2026.6.1) ...
Setting up cloudflared (2026.6.1) ...
Processing triggers for man-db (2.10.2-1) ...

In [135]:
!streamlit run app.py >/content/log.txt 2>&1 &

In [ ]:
!cloudflared tunnel --url http://localhost:8501

2026-06-25T14:15:43Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-06-25T14:15:43Z INF Requesting new quick Tunnel on trycloudflare.com...
2026-06-25T14:15:46Z INF +--------------------------------------------------------------------------------------------+
2026-06-25T14:15:46Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2026-06-25T14:15:46Z INF |  https://topics-pest-evans-fioricet.trycloudflare.com                                      |
2026-06-25T14:15:46Z INF +--------------------------------------------------------------------------------------------+
2026-06-25T14:15:46Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2026-06-25T14:15:46Z INF Version 2026.6.1 (Checksum 5861a10a438fe8ddcfebb3b830f83966cbf193edafce0fe2eeb198fbae1f7a22)
2026-06-25T14:15:46Z INF GOOS: linux, GOVersion: go1.26.4, GoArch: amd64
2026-06-25T14:15:46Z INF Settings: map[ha-connections:1 protocol:quic url:http://localhost:8501]
2026-06-25T14:15:46Z INF cloudflared will not automatically update if installed by a package manager.
2026-06-25T14:15:46Z INF Generated Connector ID: 8780726a-7087-4454-8bd4-295cb6fd209f
2026-06-25T14:15:46Z INF Initial protocol quic
2026-06-25T14:15:46Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-06-25T14:15:46Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026/06/25 14:15:46 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2026-06-25T14:15:46Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-06-25T14:15:46Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-06-25T14:15:46Z INF Starting metrics server on 127.0.0.1:20241/metrics
2026-06-25T14:15:46Z INF Tunnel connection curve preferences: [X25519MLKEM768 CurveID(65074) CurveP256] connIndex=0 event=0 ip=198.41.200.193
2026-06-25T14:15:47Z INF Registered tunnel connection connIndex=0 connection=1be3d6cb-a2e8-4fba-acd4-2cff5557abaf event=0 ip=198.41.200.193 location=atl10 protocol=quic
2026-06-25T14:15:52Z INF +-------------------------------------------------------------------------------------+
2026-06-25T14:15:52Z INF |                               CONNECTIVITY PRE-CHECKS                               |
2026-06-25T14:15:52Z INF +-------------------------------------------------------------------------------------+
2026-06-25T14:15:52Z INF |  COMPONENT         TARGET                     STATUS  DETAILS                       |
2026-06-25T14:15:52Z INF |  DNS Resolution    region1.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-06-25T14:15:52Z INF |  DNS Resolution    region2.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-06-25T14:15:52Z INF |  UDP Connectivity  region1.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-06-25T14:15:52Z INF |  UDP Connectivity  region2.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-06-25T14:15:52Z INF |  TCP Connectivity  region1.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-06-25T14:15:52Z INF |  TCP Connectivity  region2.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-06-25T14:15:52Z INF |  Cloudflare API    api.cloudflare.com:443     PASS    API is reachable              |
2026-06-25T14:15:52Z INF |                                                                                     |
2026-06-25T14:15:52Z INF |  SUMMARY: Environment is healthy. cloudflared will use 'quic' as primary protocol.  |
2026-06-25T14:15:52Z INF +-------------------------------------------------------------------------------------+
2026-06-25T14:15:52Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=181c2a8e-4f4f-48a8-acc8-10979a75f666 status=pass target=region1.v2.argotunnel.com
2026-06-25T14:15:52Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=181c2a8e-4f4f-48a8-acc8-10979a75f666 status=pass target=region2.v2.argotunnel.com
2026-06-25T14:15:52Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=181c2a8e-4f4f-48a8-acc8-10979a75f666 status=pass target=region1.v2.argotunnel.com
2026-06-25T14:15:52Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=181c2a8e-4f4f-48a8-acc8-10979a75f666 status=pass target=region2.v2.argotunnel.com
2026-06-25T14:15:52Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=181c2a8e-4f4f-48a8-acc8-10979a75f666 status=pass target=region1.v2.argotunnel.com
2026-06-25T14:15:52Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=181c2a8e-4f4f-48a8-acc8-10979a75f666 status=pass target=region2.v2.argotunnel.com
2026-06-25T14:15:52Z INF precheck component="Cloudflare API" details="API is reachable" run_id=181c2a8e-4f4f-48a8-acc8-10979a75f666 status=pass target=api.cloudflare.com:443
2026-06-25T14:15:52Z INF precheck complete hard_fail=false run_id=181c2a8e-4f4f-48a8-acc8-10979a75f666 suggested_protocol=quic
2026-06-25T14:16:12Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp [::1]:8501: connect: connection refused" connIndex=0 event=1 ingressRule=0 originService=http://localhost:8501
2026-06-25T14:16:12Z ERR Request failed error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp [::1]:8501: connect: connection refused" connIndex=0 dest=https://topics-pest-evans-fioricet.trycloudflare.com/ event=0 ip=198.41.200.193 type=http
2026-06-25T14:16:12Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp [::1]:8501: connect: connection refused" connIndex=0 event=1 ingressRule=0 originService=http://localhost:8501
2026-06-25T14:16:12Z ERR Request failed error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp [::1]:8501: connect: connection refused" connIndex=0 dest=https://topics-pest-evans-fioricet.trycloudflare.com/favicon.ico event=0 ip=198.41.200.193 type=http